#configure multi-container zrdouane<rdouanezakaria@gmail.com>
version : '3.8'
services:
  nginx:
    container-name
  image:
    nginx
  depends_on:
    - wordpress
  build:
    context:  ./requirements/nginx
    dockerfile: Dockerfile
  restart: on-failure
  ports:
    - "443:443"
networks:
  - inception
env:

